name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: FinModelUtility

    - name: Build
      run: dotnet build --no-restore
      working-directory: FinModelUtility
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      working-directory: FinModelUtility     

    - name: BinarySchema Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: 'FinModelUtility/BinarySchema Tests/TestResults/lcov.info'
        base-path: 'FinModelUtility/BinarySchema Tests'
    - name: Fin Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: 'FinModelUtility/Fin Tests/TestResults/lcov.info'
        base-path: 'FinModelUtility/Fin Tests'
    - name: Mod2Fbx Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: 'FinModelUtility/Mod2Fbx Tests/TestResults/lcov.info'
        base-path: 'FinModelUtility/Mod2Fbx Tests'